export type DnsRegion = { code: string; name: string };

// DNS uses the same city codes in its official /shops/<code>/ sections and
// in the city_path cookie that selects the regional catalogue.
export const DNS_REGIONS: DnsRegion[] = [
  { code: "arkh", name: "Архангельск" },
  { code: "astrahan", name: "Астрахань" },
  { code: "barnaul", name: "Барнаул" },
  { code: "belgorod", name: "Белгород" },
  { code: "blagoveshensk", name: "Благовещенск" },
  { code: "bryansk", name: "Брянск" },
  { code: "velikiy-novgorod", name: "Великий Новгород" },
  { code: "vladivostok", name: "Владивосток" },
  { code: "vladimir", name: "Владимир" },
  { code: "volgograd", name: "Волгоград" },
  { code: "vologda", name: "Вологда" },
  { code: "voronezh", name: "Воронеж" },
  { code: "groznyi", name: "Грозный" },
  { code: "ekaterinburg", name: "Екатеринбург" },
  { code: "ivanovo", name: "Иваново" },
  { code: "izhevsk", name: "Ижевск" },
  { code: "irkutsk", name: "Иркутск" },
  { code: "kazan", name: "Казань" },
  { code: "kaliningrad", name: "Калининград" },
  { code: "kemerovo", name: "Кемерово" },
  { code: "kirov", name: "Киров" },
  { code: "krasnodar", name: "Краснодар" },
  { code: "krasnoyarsk", name: "Красноярск" },
  { code: "kursk", name: "Курск" },
  { code: "lipetsk", name: "Липецк" },
  { code: "makhachkala", name: "Махачкала" },
  { code: "moscow", name: "Москва" },
  { code: "murmansk", name: "Мурманск" },
  { code: "naberezhnye-chelny", name: "Набережные Челны" },
  { code: "nalchik", name: "Нальчик" },
  { code: "nizhniy-novgorod", name: "Нижний Новгород" },
  { code: "novokuznetsk", name: "Новокузнецк" },
  { code: "novosibirsk", name: "Новосибирск" },
  { code: "omsk", name: "Омск" },
  { code: "orel", name: "Орёл" },
  { code: "orenburg", name: "Оренбург" },
  { code: "penza", name: "Пенза" },
  { code: "perm", name: "Пермь" },
  { code: "petrozavodsk", name: "Петрозаводск" },
  { code: "pskov", name: "Псков" },
  { code: "rostov-na-donu", name: "Ростов-на-Дону" },
  { code: "ryazan", name: "Рязань" },
  { code: "samara", name: "Самара" },
  { code: "spb", name: "Санкт-Петербург" },
  { code: "saransk", name: "Саранск" },
  { code: "saratov", name: "Саратов" },
  { code: "sevastopol", name: "Севастополь" },
  { code: "simferopol", name: "Симферополь" },
  { code: "smolensk", name: "Смоленск" },
  { code: "sochi", name: "Сочи" },
  { code: "stavropol", name: "Ставрополь" },
  { code: "surgut", name: "Сургут" },
  { code: "tambov", name: "Тамбов" },
  { code: "tver", name: "Тверь" },
  { code: "tolyatti", name: "Тольятти" },
  { code: "tomsk", name: "Томск" },
  { code: "tula", name: "Тула" },
  { code: "tumen", name: "Тюмень" },
  { code: "ulan-ude", name: "Улан-Удэ" },
  { code: "ufa", name: "Уфа" },
  { code: "khabarovsk", name: "Хабаровск" },
  { code: "cheboksary", name: "Чебоксары" },
  { code: "chelyabinsk", name: "Челябинск" },
  { code: "chita", name: "Чита" },
  { code: "yakutsk", name: "Якутск" },
  { code: "yaroslavl", name: "Ярославль" },
];

export function dnsRegionByCode(code: string | null | undefined) {
  const normalized = code?.trim().toLocaleLowerCase("en") ?? "";
  return DNS_REGIONS.find((region) => region.code === normalized) ?? null;
}
